name: pixelate
version: 0.1.0
authors:
- Don Olmstead
- Ali Akbar
description: A collection of polymer components for web application developers.
homepage: https://github.com/donny-dont/Pixelate
dependencies:
  logging: any
  polymer: any
dev_dependencies:
  mustache: any
  pixelate_flat:
    path: ../pixelate-flat
  unittest: any
  path: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/components/accordion/index.html
    - web/components/button/index.html
    - web/components/expander/index.html
    - web/components/flex_panel/index.html
    - web/components/grid_panel/index.html
    - web/components/list_view/index.html
    - web/components/progress_bar/index.html
    - web/components/scroll_viewer/index.html
    - web/components/tab/index.html
    - web/components/tree_view/index.html
    - web/getting_started/index.html
    - example/graph/graph_demo.html
