name: pixelate
version: 0.1.0
authors:
- Don Olmstead
- Ali Akbar
- Dan Ristic
description: A collection of polymer components for web application developers.
homepage: https://github.com/donny-dont/Pixelate
dependencies:
  logging: any
  polymer: 0.10.0-pre.9<0.11.0
dev_dependencies:
  mustache: any
  path: any
  pixelate_flat:
    path: ../pixelate-flat
  unittest: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/components/accordion/index.html
    - web/components/auto_complete/index.html
    - web/components/button/index.html
    - web/components/expander/index.html
    - web/components/flex_panel/index.html
    - web/components/grid_panel/index.html
    - web/components/list_view/index.html
    - web/components/progress_bar/index.html
    - web/components/scroll_viewer/index.html
    - web/components/tab/index.html
    - web/components/tooltip/index.html
    - web/components/tree_view/index.html
    - web/getting_started/index.html
    - example/graph_canvas/index.html
    - example/list_view/index.html
    - example/tree_view/index.html
